#!/bin/bash

######################################################
### Configuration
######################################################
PID="/var/run/gollum-server.pid"

# The location of the git repository
WIKI="/home/sogeuni/www/gollum-wiki/wiki/"

# The location if the gollum executable
DEAMON="/usr/local/bin/gollum"

# --config   : the location of your config file
#DEAMON_OPT="--config /home/sogeuni/www/gollum/config.rb"
#DEAMON_OPT="--adapter rugged --live-preview --h1-title --emoji --template-dir /home/sogeuni/www/gollum-wiki/templates"
DEAMON_OPT="--adapter rugged --live-preview --h1-title --template-dir /home/sogeuni/www/gollum-wiki/templates"
# The user the git repository belongs to
USER="sogeuni"
# The group the git repository belongs to
GROUP="sogeuni"

######################################################
### Script
######################################################

case "$1" in
  start)
    echo "Starting Gollum"
    start-stop-daemon --start --quiet -b -m -p $PID --chuid $USER:$GROUP --chdir $WIKI --exec $DEAMON -- $DEAMON_OPT
  ;;
  stop)
    echo "Stopping Gollum"
    start-stop-daemon --stop --quiet --pidfile $PID
    rm -f $PID
  ;;
  *)
    echo "Usage: service gollum {start|stop}"
    exit 1
  ;;
esac
exit 0
